# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f21612684141ba0a65a050b
